config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'

  scope module: :public do
    resources :items, only: [:index, :show]
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/mypage' => 'customers#update'
    get 'customers/quit' => 'customers#quit'
    patch 'customers/deactive' => 'customers#deactive'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    
    resources :orders, only: [:new]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:create, :index, :show]
    
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all
    # @order_detail = @orders.order_detail
  end
  
  private
  # ストロングパラメータ
  def top_params
    params.require(:top).permit(:image, :name, :introduction, :price, :id)
  end
  
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<!--customersのordersの一覧-->
<h2>注文履歴一覧</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
    </tr>
  </thead>

  <tbody>
    <!--customerの注文履歴一覧-->
    <% @orders.each do |order| %>
    <tr>
      <td>
        <!--customerが商品を購入した(orderをcreateした)日時-->
        <%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order.id) %>
      </td>
      <td>
        <!--注文したcustomerのfull_name-->
        <%= order.customer.full_name %>
        </td>
      <td>
        <!--注文した商品の個数-->
        <%= order.total_amount %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>